
config-version: 2

name: "dbt_nostream"
version: "1.0.0"
require-dbt-version: ">=1.5.0"

profile: dbt_nostream

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  dbt_nostream:
    +schema: raw

models:
  dbt_nostream:
    staging:
      +materialized: view
    marts:
      +materialized: view
