config-version: 2

name: "dbt_nostream"
version: "1.0.0"
require-dbt-version: ">=1.5.0"

profile: dbt_nostream

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"
  bigquery_source_project: "replit-gcp"
  bigquery_source_dataset: "Nostr"
  bigquery_flat_dataset: "Nostr"
  lookback_days: 3
  flat_incremental_strategy: "insert_overwrite"
  shared_schemas:
    - "Nostr"

seeds:
  dbt_nostream:
    +schema: raw

models:
  dbt_nostream:
    flat:
      +materialized: incremental
      +schema: "Nostr"
      +partition_by:
        field: ingestion_date
        data_type: date
        granularity: day
      +cluster_by: ["kind"]
      +incremental_strategy: "{{ var('flat_incremental_strategy', 'insert_overwrite') }}"
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: int
    marts:
      +materialized: view
      +schema: marts
