
config-version: 2

name: "jaffle_shop"
version: "1.0.0"
require-dbt-version: ">=1.5.0"

profile: default

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

seeds:
  jaffle_shop:
    +schema: raw
    jaffle-data:
      +enabled: "{{ var('load_source_data', false) }}"

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
