dbt_nostream:
  target: stage
  outputs:
    stage:
      type: bigquery
      method: service-account-json
      keyfile_json: GCP_SERVICE_ACCOUNT_CREDENTIALS
      project: replit-gcp
      dataset: dbt_nostream_stage
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      
    prod:
      type: bigquery
      method: service-account-json
      keyfile_json: GCP_SERVICE_ACCOUNT_CREDENTIALS
      project: replit-gcp
      dataset: dbt_nostream_prod
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
