dbt_nostream:
  target: stage
  outputs:
    stage:
      type: bigquery
      method: service-account
      keyfile_json: "{{ env_var('GCP_SERVICE_ACCOUNT_CREDENTIALS') }}"
      project: replit-gcp
      dataset: dbt_nostream_stage
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1

    prod:
      type: bigquery
      method: service-account
      keyfile_json: "{{ env_var('GCP_SERVICE_ACCOUNT_CREDENTIALS') }}"
      project: replit-gcp
      dataset: dbt_nostream_prod
      threads: 8
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1

    test:
      type: bigquery
      method: service-account
      keyfile_json: "{{ env_var('GCP_SERVICE_ACCOUNT_CREDENTIALS') }}"
      project: replit-gcp
      dataset: dbt_nostream_test
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive
      retries: 1
